### ISSUE TITLE
grüner server icon auf startseite im footer

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#10]
meinst du wir könnten im footer noch ein button hintun, der nochmal den impuls gibt, dass websiten nicht immer öko sind ;) also sowas wie das: https://www.fatcow.com/green-certified/hosting-badge-1.png

**Comment by raph-ael** [comment]
auf jeden fall, dewegen wird ja unter anderem auch alles auf manitu umgezogen, der aktuelle hoster macht ehrlich gesagt eher reen washin als das er wirklich gren it, also vielleicht nach dem umzug damit es auch sicher stimmt!?

**Comment by livingutopia** [comment]
wunderbar!
also wenn sowieso umgezogen wird auf manitu, dann können wir ja auch schon jetzt den icon drauf nehmen ;)
