### ISSUE TITLE
auszeichnung kleiner auf sidebar

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#11]
es wäre super, wenn die auszeichnungen kleiner angezeigt werden könnte, sodass es mit der anzeige der VIER projekte abschließt. das ganze natürlich wie bei den stimmen als sliderfunktion damit wir noch andere auszeichnungen reinbringen können ;)

**Comment by raph-ael** [comment]
okay, also cih hab dafür den huge it slider benutzt, da könnt ihr jtezt bilder posts und links hinzufügen..
