### ISSUE TITLE
github in navileiste?

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#13]
meinst du nicht es wäre sinnvoller, wenn wir github oben rausnehmen in der navileiste, weil sicherlich 99.9% damit überfordert sind, oder?

**Comment by raph-ael** [comment]
wie ihr wollt, die meisnten kennen das nciht, das stimmt, die die es kennen freuen sich umso mehr das ihr opensource seid ;) wie ihr mögt

**Comment by livingutopia** [comment]
eigentlich schon großartig, nur würde ich es nicht direkt in die obere navileiste tun, sondern ein bisschen dezenter :) vielleicht einfach so in den footer?
