### ISSUE TITLE
veranstalter*in

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#16]
irgendwie heißt es wieder nur "veranstalter", wirklich schön wäre "Veranstalter*in". kannst du das nochmal einstellen? wäre großartig :)

**Comment by raph-ael** [comment]
das lag wohl auch an nem update für das events plugin, also falls die plugins hueman oder the events calendar ein update wollen, kurz bescheid geben, dann sichere ich die sprachdateien vorher.
