### ISSUE TITLE
dynamische längen auf der startseite

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#18]
dadurch, dass es insgesamt eine dynamische anpassung der ganzen länge der startseite und der damit verbundenen sidebar gibt, passiert es, dass wenn beispielsweise die unterschiedlich langen texte bei den stimmen nacheinander im slider kommen, sich das unten stehende nach unten verschiebt ... war das verständlich was ich meinte?!

**Comment by raph-ael** [comment]
klaro, ja also das ist ein bisschen das schwieige am responsive layouten, man kann eben nicht absehen in welcher größe die seite angeschaut wird und somit die elemnte auch nciht fixieren.
ich finds ehrlich gesagt nicht soo schlimm und eigentlihc sehr gut hinbekommen, aber man könnte ein bisschen tricksen, z.B. mit javascript die höhe des längsten textes ermitteln und dann alle anderen gleich hoch machen, so entsteht dann eben ein bisschen leerer raum bei den kürzeren texten..

das gleiche passiert ja auch beim home slider.. dort könnte man überschrift auf eine zeile unt teaser text auf 2 zeilen beschränken und danach ... einfügen wenn der text zu lang ist, aber eigentlich ist ja auch der text wichtig.. 
hm man kann es ja mal ausprobieren, aber wie gesagt ich finds vielleciht sogar ein bisschen schick wird ja auch so ganz smooth animiert dann alles nach unten geschoben..

**Comment by livingutopia** [comment]
ja, ist wirklich ganz smooothy :D 
ne, dann ist super so! kannst es gerne so lassen :)
danke dir :*
