### ISSUE TITLE
alwizuko auf startseite ist weg?

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#19]
unter "Projekte" auf der Startseite fehlt das "alwizuko". habe eben geschaut: es ist unter der Kategorie "Projekte" eingeordnet, also müsste eigentlich auftauchen?

**Comment by raph-ael** [comment]
unter einstellungen -> home categories sind die kategorien ausgewählt die nicht auf der startseite auftauchen sollen, da war irgendwie alwizuko angeklickt..

**Comment by livingutopia** [comment]
ah, okey. wunderbar :)
