### ISSUE TITLE
beiträge "aktivist*innen" ohne datum und autor*in

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#20]
können die Aktivist_innen-Seiten (unter "wer wir sind" auf "mehr" bei den jeweiligen Personen) ohne Datum und Autor_in angezeigt werden?
können wir das auch einstellen?

**Comment by raph-ael** [comment]
na logo!

damit ich die alle per css ansprechen kann bitte folgendes machen:

alle utopist*innen als seite anlegen und als eltern seite "wer wir sind" auswählen,
dann natürlich noch den link unter benutzer bearbeiten anpassen,
hab das mal bei pia examplarisch gemacht,
ihr dürft als weiter icon auch gerne eines hieraus auswählen: http://fortawesome.github.io/Font-Awesome/cheatsheet/ 
dann einfach in den i tag das entity eintragen also z.B.

```
<a href="/wir/wer-wir-sind/pia/">... mehr <i>&#xf061;</i></a>
```

**Comment by livingutopia** [comment]
wuuunderbar! dankeschön :)
die kleinen Details, die du geändert hast, sind richtig toll!
jetzt fehlt nur noch der wundervolle utopist Raphi... ;)

**Comment by raph-ael** [comment]
:) sehr gerne danke euch!
ich beantworte einfach mal diese 3 fragen... und gleich geht es los was uiuiuui! :)

jetzt mache ich noch shcnell meinen blog über die hacker reise geldfrei.net fertig. dann gibts gleich 2 realeses..

beherzte grüßee!

**Comment by livingutopia** [comment]
raphiiii ich habe deinen text nur überflogen, aber er hat mein herz erwärmt. danke diiir <3 sooo schön!
