### ISSUE TITLE
launch um 20.15h?

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#22]
was meinst du?

**Comment by raph-ael** [comment]
wir können nur noch wrten... nameserver sind schon alle umgestellt, das dauert manchal ein wenig.. deswegen ist auch jetzt schonmal die webdev. nciht mehr zu erreichen...

**Comment by livingutopia** [comment]
wunderbar! danke dir herzlichst :) sind soooo gespannt :) <3 - lichsten dank!
