### ISSUE TITLE
bilder der utopist*innen unterschiedlich groß

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#23]
eben fügte ich marius als benutzer ein und sein bild ist - obwohl klein und wenige pixelanzahl - nun größer angezeigt. weißt du wieso? ist es möglich das für alle gleich einzustellen? :)

**Comment by raph-ael** [comment]
japps, also es macht immer alle bilder auf die gleiche höhe, wir sollten einfach ein format festlegen, man kann im backend einstellen wenn man ein bild aus der library auswählt und dann auf bild bearbeiten klickt kann mans manuell skallieren,
dann ein bereich auswählen der ungefair angezeigt werden soll und dann links das format exakt festlegen. wie wäre es mit 4:5 ? das passt ganz gut glaub ich müssten einfach alle bilde rungefähr hochformatig sein.

**Comment by livingutopia** [comment]
wunderbar, hört sich super an :)
dann können wir online gehen oder?
wir haben alles nochmal gründlich gecheckt und sind sooo glücklich und aufgeregt - auch auf das feedback :) die seite ist einfach wunderschöN!!!

**Comment by raph-ael** [comment]
mir ist noch was aufgefallen, ihr habt ein paar wenige fotos als png hochgeladen, diese können leider nciht so gut bearbeitet werden vom webserver, z.B. das bild von pia.
das ist dann in den abmesungen sehr klein aber trotzdem knapp 1mb groß, wenn ihr es schaffen würdet die vor dem hochladen immer als jpg abzuspeichern wäre das ganz prima..
im zweifelsfall gibts auch online services die einem das machen (http://www.fixpicture.org/index.php?LANG=de)
