### ISSUE TITLE
kickoff?!

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#24]
ist das normal, dass nach und nach dann noch fotos nachgeladen werden?! und das die medienberichte - logos - jetzt ein wenig vercheckt auf der startseite sind ...
was meinst du?

**Comment by raph-ael** [comment]
teilweise hat es absolute urls eingebaut (also http://webdev.living..) und findet die bilder nicht mehr, ihr könntet z.B. gerade mal das mit den benutzerbildern machen und gleich auf 4:5 skalieren, ich gucke beim rest..

**Comment by raph-ael** [comment]
jetzt schaut alles schon ganz prima aus :)
eine kleinigkeit noch, wenn ihr bilder am anfang rechts oder linksbündig einfügt achtet darauf das sie auch im quelltext ganz am anfang stehen, sonst sieht es auf dem handy so aus:
![piamob](https://cloud.githubusercontent.com/assets/7235821/4691039/980a4d48-5703-11e4-9083-75a88d42dd7a.png)

und danke vielmals fürs text korrigieren gendern ;)
ich bin auch ganz glücklich mit der seite!!

**Comment by livingutopia** [comment]
ah, wunderbar! gut, dass du's sagst, werden wir drauf achten :)
ich hoffe, das text korrigieren, war wirklich ok?
wir haben bei allen und in jedem text gegendert, daher... ;)
viiiel sonne aus weilheim :)
