### ISSUE TITLE
subdomains?!

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#26]
es ist voll wichtig, dass die subdomains wie:
alwizuko.livingutopia.org und tagderutopie.livingutopia.org funktionieren :)
meinst du, dass das leicht machbar ist?

**Comment by raph-ael** [comment]
oha klaro, ihc hab sie der schnelle halber wieder zurück geleitet zum alten server, ziehen wir dann später auch zu manitu um.. also sollten gleich wieder funktionieren..
