### ISSUE TITLE
zugangsdaten für daniel

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#27]
magst du noch uns die zugangsdaten für den server geben, damit daniel die subdomains verändern kann?!

**Comment by livingutopia** [comment]
heyho lieber raphi :)
wir werden vermutlich am 1.11. ein neues miniprojekt starten. und zwar "der vegane kochlöffel".
dafür ist daniel gerade dabei eine website zu basteln: http://camp2015.de/derveganekochlo%CC%88ffel/
es wäre deswegen super gut, wenn du kurzerhand an mich oder direkt daniel die zugangsdaten sendest :)
herzlichsten dank dir und viel freude weiterhin auf deiner wunderbaren reise.
jeden tag lese ich ganz eifrig den wunderbaren blog!

**Comment by raph-ael** [comment]
die zugangsdaten sind noch die alten ftp daten wie gehabt, lediglich die lu haupseite ist jetzt bei manitu. ich muss nur ein dns eintrag pro sub domain anlgen, hab jetzt mal veganerkochloeffel.livingutopia ins entprechende verzeichnis geleitet.

findet ihr nicht auch diese ganzen verstreuten seiten noch nciht so ganz optimal? Ich habe gesehn es gibt ein plugin für wordpress das subdomains routen kann, für jede subdomain kann auch ein eigenes template geladen werden, so könnte daniel vielleicht einfach mini wordpress templates bauen und zusätzlich könnte man sich ein menü oder so etwas überlegen das z.B. fixiert ganz oben auf jedem one pager angezeigt wird über das die menschen immer direkt zwischen den projektseiten und livinutopia teise switchen können...

oder etwas anders aber irgendein element reinbringen um dem ganzen den berühmten roten faden zu geben... :)

**Comment by livingutopia** [comment]
super, dass du so schnell zurückschreibst.
prinzipiell eine wunderbare idee. können wir einfach mal angehen, aber sicherlich ein längeres unterfangen.
für die "der vegane kochlöffel" seite möchten wir dann prinzipiell eine eigene domain freischalten lassen. also www.derveganekochloeffel.de :) greensta haben wir einfach mal angefragt, weil die damals ja sehr offen waren.
wie können wir daniel zu diesem github einladen, damit er mitdenken und mitschnacken kann?
achja und wieso geht: http://deineidee.livingutopia.org noch nicht? lag das nicht an dem serverumzug?
danke dir sehr!

**Comment by raph-ael** [comment]
jetzt gehts :)
also daniel braucht einfach einen github login und dann kann er dem projekt https://github.com/raph-ael/livingutopia.org folgen

**Comment by livingutopia** [comment]
super gut :) da wird sich der liebe daniel sicher mal einloggen und dann melden :)

**Comment by danielm23** [comment]
Hier ist der liebe Daniel :)

**Comment by livingutopia** [comment]
juhuuu! dann kannst du dich nun ja mit dem lieben raphi direkt auseinandersetzen! :)

**Comment by danielm23** [comment]
oh ja, die alten zugangsdaten gehen noch. es lag lediglich daran, dass ich statt der ip die lu domain eingetragen hatte. mit der ip direkt funktioniert alles prima. und ja - das mit den ganzen subdomains finde ich auch noch nicht so optimal. welches plugin meinst du denn?

**Comment by raph-ael** [comment]
das hier z.B. https://wordpress.org/plugins/wp-subdomains-revisited/screenshots/ da kann man sagen das eine blog kategorie eine einzelne seite oder ein_e author_in als subdomain zu erreichen ist und welches theme diese dann benutzen soll.. das klingt doch ganz gut oder?
