### ISSUE TITLE
kontaktformular verlinken

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#3]
wie könnte ich das kontaktformular: http://webdev.livingutopia.org/kontaktformular/
mit dem bisher noch nicht funktionieren mailbutton verlinken?

**Comment by raph-ael** [comment]
ahja lustig da war ich azch gerade dran, also im wp-admin unter design => theme options => social links

**Comment by livingutopia** [comment]
perfekt! danke!
