### ISSUE TITLE
umzug auf den greensta server?

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#34]
heyho ihr lieben :)
unser Mailpostfach quillt über und da wir nun ja bei greensta einiges an Platz haben, wäre es doch sicherlich sinnvoll umzuziehen, oder?
wunderbar wäre es auch, wenn da im footer der livingutopia.org Website das "hostet by Greensta" - Logo wäre :)
Was meint ihr?

**Comment by livingutopia** [comment]
99% des Mailpostfachs sind voll und leider gibt es keine Möglichkeit noch mehr zu löschen ;)
Was meinst du - Raphi - wie aufwändig so ein Umzug wäre?
Herzlichsten Dank und besten Gruß,
tobi

**Comment by raph-ael** [comment]
hallo ihr lieben.. ich bin zurück aus paris. habe eure emails umgezogen, d.h. alle aktuellen mails liegen nun bei greensta also ab jetzt nicht mehr das alte konto benutzen, ihr könnt es getrost aus eurem thunderbird löschen. 
im thunderbird ein neuen konto anlegen mit dem zugang zu livingutopia@derveganekochloeffel.de dortlanden alle emails. unter identitäten könnt ihr dann eure gewünschten absender eintragen, damit da auch als absender eure @livingutopia emailadresse steht..

herzlichste grüße und alles liebe!!!

**Comment by livingutopia** [comment]
wooow! danke dir herzlichst :)
du warst in paris? super schön :) wie kamst du dahin :)

wie genau stellen wir das neue konto ein? gibt es da nicht ein pw, was wir noch brauchen?
und sind da dann auch noch die alten mails?

danke dir von tiefstem herzen :) nun haben wir dann mal wieder platz :)

liebste grüße und bis ganz ganz bald,
tobi

**Comment by livingutopia** [comment]
perfekt! einfach super gut!!!
nun läuft alles wie am schnürrchen ;)
