### ISSUE TITLE
startseiten sidebar neues element

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#5]
rechts unter den stimmen noch soetwas wie "auszeichnungen": da kann dann so eine datei angezeigt werden:
--> http://www.cajos.de/wp/wp-content/uploads/2010/11/Logo_UN-Dekade_BeitragNEU_cmyk.jpg

**Comment by raph-ael** [comment]
ist drin und bearbeitbar unter design => widgets.. ich finds ein wenig sehr blau.. oder?
