### ISSUE TITLE
designidee auf startseite

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#7]
was hälst du davon, wenn auf der startseite sowohl bei "news" als auch bei "projekte" ein grüner button (ob rund oder länglich) untergelegt wird, damit besser erkenntlich ist, wo was anfängt ... 
was meinst du?
![idee](https://cloud.githubusercontent.com/assets/9282093/4678531/6d21cf3c-55f7-11e4-82ec-1574a58e8d14.png)

**Comment by raph-ael** [comment]
joa find ich chick, ich würds auch fals als kleine grafiische spielerei auf allen seiten drin lassen was meint ihr?

**Comment by livingutopia** [comment]
super gut! kann geclosed werden :) du bist ja verrückt! so spät noch wach!!!
