### ISSUE TITLE
bilderansicht evaluieren

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#8]
die bilderansicht im allgemeinen ist noch suboptimal wie bspw. hier: http://webdev.livingutopia.org/utopival/die-welt/

**Comment by raph-ael** [comment]
dort wo ihr die gallerie in einen beitrag einfügt klickt ihr auf die optionen (editier stift oben links)
dann auf der rechten seite unter "Gallerie-Einstellungen" Link zur: Mediendatei auswähnen
![galleryoption](https://cloud.githubusercontent.com/assets/7235821/4681335/2141942e-5612-11e4-8c56-f89834c66140.png)
