### ISSUE TITLE
newslettereintragungsbestätigungsmail ist spam?!

### ISSUE THREAD

**Issue by livingutopia** [raph-ael/livingutopia.org#9]
kannst du dir vorstellen, warum die bestätigungsmail beim eintragen in den newsletter als spam deklariert wird?

**Comment by raph-ael** [comment]
also ists bei mir nicht ich hatte ssl verschlüsselng aktiviert und das lief über nicht dieselbe domain wie die von der mail adresse selbst, hab mal auf unverschlüsselt umgestellt.
gibts eine veränderung?
